[package]
name = "image-dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.23", features = ["derive"] }
flate2 = "1.0.35"
image = "0.25.5"
serde = "1.0.217"
serde_json = "1.0.134"
